server:
  port: 8080

database:
  # Use the service name 'postgres' as the host.
  dsn: "postgresql://user:password@postgres:5432/shortener?sslmode=disable"

redis:
  # Use the service name 'redis' as the host.
  addr: "redis:6379"
  password: ""
  db: 0

auth:
  session_key: "n0yLf5N2vVZ2mQdnjZi8fU7GBYTMumep"