server:
  port: 8080

database:
  # This is a standard PostgreSQL connection string (DSN)
  # Format: postgresql://user:password@host:port/dbname?sslmode=disable
  dsn: "postgresql://user:password@localhost:5432/shortener?sslmode=disable"