
server:
  port: 8080

database:
  dsn: "postgresql://user:password@localhost:5432/shortener?sslmode=disable"

redis:
  addr: "localhost:6379"
  password: "" # no password set
  db: 0 # use default DB