// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: clicks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClick = `-- name: CreateClick :one
INSERT INTO clicks (
    link_id,
    ip_address,
    user_agent,
    referrer
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, link_id, clicked_at, ip_address, user_agent, referrer
`

type CreateClickParams struct {
	LinkID    int64
	IpAddress pgtype.Text
	UserAgent pgtype.Text
	Referrer  pgtype.Text
}

func (q *Queries) CreateClick(ctx context.Context, arg CreateClickParams) (Click, error) {
	row := q.db.QueryRow(ctx, createClick,
		arg.LinkID,
		arg.IpAddress,
		arg.UserAgent,
		arg.Referrer,
	)
	var i Click
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.ClickedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.Referrer,
	)
	return i, err
}
