// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Click struct {
	ID        int64
	LinkID    int64
	ClickedAt pgtype.Timestamptz
	IpAddress pgtype.Text
	UserAgent pgtype.Text
	Referrer  pgtype.Text
}

type Link struct {
	ID           int64
	Alias        string
	OriginalUrl  string
	PasswordHash []byte
	ExpiresAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	UserID       pgtype.Int8
}

type User struct {
	ID           int64
	Email        string
	PasswordHash []byte
	CreatedAt    pgtype.Timestamptz
}
